### ISSUE TITLE
ubridge

### ISSUE THREAD

**Issue by homerASM** [jeffreystoke/docker-cisco-lab#1]
hello,

I have a problem after adding a new device in GNS3-GUI.
 When i try to start the device in GNS3-GUI
The console display this error:

**# error while starting IOU1: Error while looking for uBridge version: [Errno 1] Operation not permitted: '/usr/local/bin/ubridge'
Error while looking for uBridge version: [Errno 1] Operation not permitted: '/usr/local/bin/ubridge'**

I get the same error when launch ubridge in the container:

**# /usr/local/bin # ls -l
total 2380
-rwxr-xr-x    1 root     root       1130760 May 23 13:14 dynamips
-rwxr-xr-x    1 root     root         86744 May 23 13:15 iouyap
-rwxr-xr-x    1 root     root         24896 May 23 13:12 nvram_export
-rwxr-xr-x    1 root     root         92864 May 23 13:15 ubridge
-rwxr-xr-x    1 root     root       1080312 May 23 13:11 vpcs
/usr/local/bin # ./ubridge
sh: ./ubridge: Operation not permitted**

Do you have any idea how to solve this problem?

With kindest regards.

**Comment by jeffreystoke** [comment]
Morning there!
Thanks for your feedback, can you provide me your os and docker version, that may help a lot.

**Comment by jeffreystoke** [comment]
@homerASM , it turns out to be a issue cause by `sudo`, which is required by the installation of `ubridge` and `iouyap`, and the root user is not the actual root. 
This issue should have been fixed with [Dockerfile#L51](https://github.com/jeffreystoke/docker-cisco-lab/blob/700466f8af895cb4101fa5a304c42917f4ea3159/Dockerfile#L51)

**Comment by homerASM** [comment]
**@jeffreystoke**, I use ubuntu 18.04 et my docker version is 17.12.1
I will use this dockerfile as soon as possible and return you the feedback.

Thank a lot for your time.

**Comment by homerASM** [comment]
**@jeffreystoke**, I have pull and run again the container.
Now, when I start the device, I have a new error:
**error while starting IOU1: uBridge executable version must be >= 0.9.14
uBridge executable version must be >= 0.9.14**
I use GNS3-GUI 2.1.6. I think that my GNS3-GUI is too new for the ubridge-container version.
Can you confirm my think?

With kindest regards.

**Comment by jeffreystoke** [comment]
@homerASM you're right, my local gns3 version is 2.1.0, I will test and update soon, alternatively, you can change the ubridge version yourself by `cd ubridge && git checkout 0.9.14` (maybe there's a `v` before `0`), and that would probably do the job, happy hacking!

**Comment by homerASM** [comment]
**@jeffreystoke** Thank you for your commit with 0.9.14 ubridge version.
All is working.

**Comment by jeffreystoke** [comment]
@homerASM you are welcome, closing this issue since problem solved, feel free to reopen it if you got any problem.
