### ISSUE TITLE
Question: Telnet/SSH into container

### ISSUE THREAD

**Issue by patilchinmay** [jeffreystoke/docker-cisco-lab#2]
Apologies if this isn't the appropriate avenue for this question. @jeffreystoke 

- Is it possible to telnet/ssh into the container and access the Cisco cli to make configuration changes ? (I am not using GNS3. I just want to simulate Cisco device and do certain cli operations such as `show run`)
- If yes, would you please be kind enough to document the process for the same ?

**Comment by jeffreystoke** [comment]
@patilchinmay there is no sshd daemon running inside the container, so it's not possible to ssh into the container unless you have installed and running ssh server (e.g. openssh server), but you can use `docker exec -it <your-container-name> bash` to get a commandline interface inside the container, I think that's more or less the same with ssh.

**Comment by jeffreystoke** [comment]
Closing due to no further information, feel free to reopen it if any question.
